apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limitrange
  namespace: dev-team
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "250m"
        memory: "256Mi"
      type: Container
